[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
    Pragma = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID = "your-project-id"
  NEXT_PUBLIC_SANITY_DATASET = "production"
  NODE_VERSION = "18"