[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "next build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID = "your-project-id"
  NEXT_PUBLIC_SANITY_DATASET = "production"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"